---
name: CI/CD React JS GitHub Pages
on:
  push:
    branches: [ dev ]
env:
  NODE_VERSION: 18.x
  GIT_USERNAME: "Deathblood69"
  GIT_EMAIL: "deathblood69002@gmail.com"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js $NODE_VERSION
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js $NODE_VERSION
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
          cache: 'npm'
      - run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js $NODE_VERSION
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
          cache: 'npm'
      - name: Deploy
        run: |
          git config --global user.name $GIT_USERNAME
          git config --global user.email $GIT_EMAIL
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
          npm run deploy